//API1

GET http://localhost:3000/todos/
####
GET http://localhost:3000/todos/?status=TO%20DO
###

GET http://localhost:3000/todos/?priority=HIGH
###

//API2
GET http://localhost:3000/todos/5/
###

//API3
POST http://localhost:3000/todos/
Content-Type: application/json

{
    "id": 3,
    "todo": "Learn React",
    "priority": "HIGH",
    "status": "TO DO"
}
####

PUT http://localhost:3000/todos/5
Content-Type: application/json

{
    "status" : "TO DO"
}
###

DELETE http://localhost:3000/todos/3
###